const app=document.querySelector('#app'),dialog=document.querySelector('#info');
const prices={small:{name:'小件',hint:'背包 / 登机箱 / 小纸箱',day:100,week:600,month:2400},medium:{name:'中箱',hint:'20–26寸',day:150,week:800,month:3000},large:{name:'大箱',hint:'27–30寸',day:250,week:1200,month:4000}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'£'+(n/100).toFixed(2);
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const plus=(d,n)=>new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
let draft={items:[{category:'medium',quantity:2}],startDate:plus(today,1),startTime:'10:00',pickupDate:plus(today,3),pickupTime:'18:00',name:'Alex（示例）',phone:'07700 900123',wechat:'alex_demo',notes:''},order=null;
function quote(d){const days=Math.round((Date.parse(d.pickupDate+'T12:00:00Z')-Date.parse(d.startDate+'T12:00:00Z'))/86400000)+1;if(!Number.isFinite(days)||days<1)return null;const m=Math.floor(days/30),w=Math.floor(days%30/7),r=days%30%7,lines=d.items.map(i=>({...i,name:prices[i.category].name,total:i.quantity*(m*prices[i.category].month+w*prices[i.category].week+r*prices[i.category].day)}));return {days,lines,total:lines.reduce((s,i)=>s+i.total,0)}}
function toast(s){const e=document.querySelector('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function info(s){document.querySelector('#info-content').innerHTML=s;dialog.showModal()}document.querySelector('.close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
function openPrices(){info('<div class="eyebrow">STORAGE RATES</div><h2>寄存价格</h2>'+Object.values(prices).map(p=>`<div class="price-row"><div class="row"><h3>${p.name}</h3><strong>${money(p.day)} / 天</strong></div><small>${p.hint}</small><small>${money(p.week)} / 周　${money(p.month)} / 30 天</small></div>`).join('')+'<p class="muted">存入日与取件日均计费。先按 30 天套餐，再按 7 天套餐，余下按日计算。</p>')}
function openStore(){info('<div class="eyebrow">BEFORE YOU ARRIVE</div><h2>门店与须知</h2><p>42 Wheeler Garden, London<br><span class="muted">King’s Cross 附近</span></p><p style="font-size:28px">09:00 — 21:00</p><p class="muted">以伦敦当地时间为准。行李整单存入、整单取出。现金、证件及贵重物品请随身携带。</p><div class="note">门店信息沿用项目资料，本演示不会产生真实预约。</div>')}
function home(){app.innerHTML=`<div class="home-grid"><section><div class="eyebrow">LONDON · KING’S CROSS</div><h1>把行李放下。<br><span>把时间留给伦敦。</span></h1><p class="muted lead">选好存取时间，轻装去逛下一站。<br>从预约到取件，安排都在这里。</p><form id="home-chat" class="home-chat"><div class="row"><strong>聊聊你的寄存安排</strong><span class="tag">AI 模拟对话</span></div><label class="sr-only" for="home-message">描述行李和存取时间</label><textarea id="home-message" maxlength="1000" placeholder="比如：两个24寸箱子，明天10点存，后天18点取"></textarea><button class="btn full" type="submit">让助手帮我生成预约单 →</button><p class="chat-disclaimer">模拟 AI · 不连接真实模型 · 不会自动提交预约</p></form><div class="actions"><a class="small-link" href="#booking">直接填写预约</a><a class="small-link" href="#orders">查看示例订单</a></div><div class="home-links"><button id="prices">查看价格 ＋</button><button id="store">门店与须知 ＋</button></div></section><div class="home-art"><div class="pass-stack"><div class="pass-back far"></div><div class="pass-back near"></div><div class="luggage-pass"><div class="pass-top"><span>行李寄存</span><span class="pass-location">LON</span></div><div class="pass-art" aria-hidden="true"><div class="case-handle"></div><div class="case-body"><i></i><i></i><i></i></div><div class="case-wheel wheel-left"></div><div class="case-wheel wheel-right"></div></div><div class="pass-bottom"><div><div class="pass-caption">从这里，轻装出发</div><div class="pass-hours">09:00 — 21:00</div></div><div class="pass-lines" aria-hidden="true"></div></div></div></div><div class="art-caption">A LITTLE LESS TO CARRY.</div></div></div>`;document.querySelector('#prices').onclick=openPrices;document.querySelector('#store').onclick=openStore;document.querySelector('#home-chat').onsubmit=e=>{e.preventDefault();const text=document.querySelector('#home-message').value.trim();if(text)sendChat(text);location.hash='chat'}}
function heading(en,title,sub){return `<section class="page-heading"><div class="eyebrow">${en}</div><h1>${title}</h1><div class="muted">${sub}</div></section>`}
function estimate(d){const q=quote(d);return `<div class="eyebrow">YOUR ESTIMATE</div><h2 style="margin-top:12px">预计寄存费用</h2><div class="amount">${q?money(q.total):'—'}</div><div class="muted">${q?q.days+' 个计费日 · '+d.items.reduce((s,i)=>s+i.quantity,0)+' 件行李':'请检查日期'}</div><div class="divider"></div>${q?q.lines.map(i=>`<div class="summary-line"><span>${i.name} × ${i.quantity}</span><span>${money(i.total)}</span></div>`).join(''):''}<div class="divider"></div><div class="summary-line"><span>存入</span><span>${esc(d.startDate)} ${esc(d.startTime)}</span></div><div class="summary-line"><span>取件</span><span>${esc(d.pickupDate)} ${esc(d.pickupTime)}</span></div><div class="note">存入日与取件日均计费。演示报价不会产生真实预约或扣款。</div>`}
function field(key,label,type='text'){return `<div class="field"><label for="${key}">${label}</label><input id="${key}" name="${key}" type="${type}" value="${esc(draft[key])}" ${type==='date'?`min="${today}" max="${plus(today,89)}"`:type==='time'?'min="09:00" max="21:00" step="900"':'maxlength="80"'} required></div>`}
function booking(){app.innerHTML=heading('YOUR BOOKING','预约寄存','填写行李与存取时间，即时查看预计费用。')+`<div class="columns"><form id="form"><section class="card"><div class="row"><h2>带了多少行李？</h2><button id="add" type="button" class="small-link">＋ 添加行李</button></div>${draft.items.map((i,n)=>`<div class="luggage-row"><div class="field"><label for="cat${n}">行李类型</label><select id="cat${n}" data-n="${n}" data-key="category">${Object.entries(prices).map(([k,p])=>`<option value="${k}" ${k===i.category?'selected':''}>${p.name} · ${p.hint}</option>`).join('')}</select></div><div class="field"><label for="qty${n}">数量</label><input id="qty${n}" type="number" min="1" max="20" value="${i.quantity}" data-n="${n}" data-key="quantity" required></div><button type="button" class="remove" data-remove="${n}" aria-label="删除行李" ${draft.items.length===1?'disabled':''}>×</button></div>`).join('')}</section><section class="card"><h2>什么时候存取？</h2><div class="field-grid">${field('startDate','存入日期','date')+field('startTime','存入时间','time')+field('pickupDate','取件日期','date')+field('pickupTime','取件时间','time')}</div><p class="muted" style="font-size:13px;margin-bottom:0">伦敦当地时间 · 09:00–21:00 · 每 15 分钟一个时段</p></section><section class="card"><h2>联系方式</h2><div class="note" style="margin-bottom:18px">使用示例信息体验即可，请勿填写真实个人信息。</div><div class="field-grid">${field('name','称呼')+field('phone','联系电话')+field('wechat','微信号')}</div><div class="field" style="margin-top:18px"><label for="notes">特殊需求（选填）</label><textarea id="notes" name="notes" maxlength="500" placeholder="如易碎、特殊摆放需求">${esc(draft.notes)}</textarea></div></section><div class="error" id="error" role="alert"></div><button class="btn full" type="submit">核对预约与费用</button></form><aside id="summary" class="card summary">${estimate(draft)}</aside></div>`;
const f=document.querySelector('#form');f.oninput=e=>{const t=e.target;if(t.dataset.n!==undefined)draft.items[+t.dataset.n][t.dataset.key]=t.dataset.key==='quantity'?Number(t.value):t.value;else if(t.name)draft[t.name]=t.value;document.querySelector('#summary').innerHTML=estimate(draft)};document.querySelector('#add').onclick=()=>{if(draft.items.length>=8)return toast('最多添加 8 类行李');draft.items.push({category:'small',quantity:1});booking()};document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{draft.items.splice(+b.dataset.remove,1);booking()});f.onsubmit=e=>{e.preventDefault();const error=validate(draft);if(error)return document.querySelector('#error').textContent=error;location.hash='review'}}
function validate(d){if(d.startDate<today||d.pickupDate>plus(today,89))return '请选择未来 90 天内的日期。';if(Date.parse(d.pickupDate+'T'+d.pickupTime)<=Date.parse(d.startDate+'T'+d.startTime))return '取件时间必须晚于存入时间。';if([d.startTime,d.pickupTime].some(t=>t<'09:00'||t>'21:00'||+t.slice(3)%15))return '请选择营业时间内的 15 分钟时段。';if(!d.items.length||d.items.some(i=>!prices[i.category]||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>20))return '每类行李数量应为 1–20 件。';if([d.name,d.phone,d.wechat].some(v=>!v.trim()))return '请补齐联系方式。';return ''}
function review(){app.innerHTML='<a class="breadcrumb" href="#booking">返回修改预约</a>'+heading('CHECK YOUR BOOKING','确认这次寄存安排','核对后提交，将生成一笔示例订单。')+`<div class="columns"><section><div class="card"><h2>预约信息</h2><div class="summary-line"><span>存入</span><strong>${esc(draft.startDate)} ${esc(draft.startTime)}</strong></div><div class="summary-line"><span>取件</span><strong>${esc(draft.pickupDate)} ${esc(draft.pickupTime)}</strong></div><div class="divider"></div>${draft.items.map(i=>`<div class="summary-line"><span>${prices[i.category].name} · ${prices[i.category].hint}</span><strong>${i.quantity} 件</strong></div>`).join('')}</div><div class="card"><h2>联系信息</h2><p>${esc(draft.name)}<br><span class="muted">${esc(draft.phone)} · ${esc(draft.wechat)}</span></p>${draft.notes?`<div class="note">${esc(draft.notes)}</div>`:''}</div><div class="note">订单仅保留在当前页面会话中，刷新后重置；不会发送给门店。</div></section><aside class="card summary">${estimate(draft)}<button class="btn full" id="submit" style="margin-top:24px">提交示例预约</button></aside></div>`;document.querySelector('#submit').onclick=()=>{const error=validate(draft);if(error){toast(error);location.hash='booking';return}order={id:'LON-DEMO-'+String(Date.now()).slice(-6),status:'pending',input:structuredClone(draft),code:'LON8K2PX',history:[{title:'预约已提交',note:'等待门店确认 · 示例订单'}]};location.hash='order';toast('示例预约已生成')}}
const names={pending:'待确认',payment:'待付款',ready:'待寄存',stored:'寄存中',completed:'已完成',cancelled:'已取消'};
function sample(){return {id:'LON-DEMO-001',status:'stored',input:structuredClone(draft),code:'LON8K2PX',history:[{title:'预约已确认',note:'门店确认存取安排 · 示例状态'},{title:'模拟付款已完成',note:'未实际扣款'},{title:'行李已寄存',note:'示例状态，等待取件'}]}}
function orders(){const o=order||sample(),q=quote(o.input);app.innerHTML=heading('YOUR ORDERS','我的订单','查看寄存进度与取件安排。')+(!order?'<div class="note" style="margin-bottom:24px">当前显示预设示例订单，也可以从预约页创建新的演示订单。</div>':'')+`<button class="card full orders-card" id="open" style="text-align:left;color:inherit"><div class="row"><h2>${esc(o.id)}</h2><span class="tag">${names[o.status]}</span></div><div class="summary-line"><span>${o.input.items.reduce((s,i)=>s+i.quantity,0)} 件行李 · ${q.days} 个计费日</span><strong>${money(q.total)}</strong></div><div class="summary-line"><span>存入 ${esc(o.input.startDate)}</span><span>取件 ${esc(o.input.pickupDate)}</span></div><div class="divider"></div><span class="small-link">查看订单详情</span></button><a class="btn secondary" href="#booking">再预约一笔</a>`;document.querySelector('#open').onclick=()=>{if(!order)order=o;location.hash='order'}}
function detail(){if(!order)order=sample();const o=order,q=quote(o.input),stage=['pending','payment','ready','stored','completed'].indexOf(o.status),action={pending:['模拟门店确认','payment'],payment:['模拟支付 '+money(q.total),'ready'],ready:['模拟登记寄存','stored'],stored:['模拟确认取件','completed']}[o.status];app.innerHTML='<a class="breadcrumb" href="#orders">返回我的订单</a>'+heading('ORDER & COLLECTION','订单与取件',esc(o.id)+' · 示例订单')+`<div class="columns"><div><section class="card"><div class="row"><h2>寄存进度</h2><span class="tag">${names[o.status]}</span></div><div class="status-steps">${['预约确认','模拟付款','到店寄存','取件完成'].map((s,i)=>`<div class="step ${stage>i?'done':''}"><b>${i+1}</b>${s}</div>`).join('')}</div><div class="divider"></div><div class="summary-line"><span>存入时间</span><strong>${esc(o.input.startDate)} ${esc(o.input.startTime)}</strong></div><div class="summary-line"><span>取件时间</span><strong>${esc(o.input.pickupDate)} ${esc(o.input.pickupTime)}</strong></div>${o.input.items.map(i=>`<div class="summary-line"><span>${prices[i.category].name} · ${prices[i.category].hint}</span><strong>× ${i.quantity}</strong></div>`).join('')}</section>${['ready','stored','completed'].includes(o.status)?`<section class="card"><div class="eyebrow">DEMO COLLECTION CODE</div><h2 style="margin-top:8px">示例取件码</h2><div class="code">${o.status==='completed'?'已核销':o.code}</div><div class="muted">${o.status==='completed'?'模拟取件完成，此码已失效。':'到店出示取件码，整单取走行李。此码仅用于演示。'}</div></section>`:''}<section class="card"><h2>订单记录</h2>${o.history.map(h=>`<div class="timeline"><span class="timeline-dot"></span><div>${esc(h.title)}<small>${esc(h.note)}</small></div></div>`).join('')}</section><section class="card"><h2>联系信息</h2><div class="summary-line"><span>称呼</span><span>${esc(o.input.name)}</span></div><div class="summary-line"><span>电话</span><span>${esc(o.input.phone)}</span></div>${o.input.notes?`<div class="note">${esc(o.input.notes)}</div>`:''}</section></div><aside class="card summary"><div class="eyebrow">BOOKING TOTAL</div><h2 style="margin-top:12px">预约费用</h2><div class="amount">${money(q.total)}</div><div class="muted">${q.days} 个计费日 · 模拟订单</div><div class="divider"></div>${q.lines.map(i=>`<div class="summary-line"><span>${i.name} × ${i.quantity}</span><span>${money(i.total)}</span></div>`).join('')}<div class="note" style="margin:20px 0">以下按钮演示订单流转。不会真实付款、通知门店或核销行李。</div>${action?`<button class="btn full" id="advance">${action[0]}</button>`:`<div class="note">${o.status==='cancelled'?'订单已取消':'本次模拟寄存已完成'}</div>`}${stage>=0&&stage<3?'<button class="btn light full" id="cancel">取消示例订单</button>':''}</aside></div>`;
if(action)document.querySelector('#advance').onclick=()=>{if(o.status==='stored'){info('<h2>确认模拟取件？</h2><p class="muted">将演示整单核销，示例取件码会失效。</p><button class="btn full" id="confirm">确认模拟取件</button>');document.querySelector('#confirm').onclick=()=>{dialog.close();advance(action[1])}}else advance(action[1])};const b=document.querySelector('#cancel');if(b)b.onclick=()=>{info('<h2>取消这笔示例订单？</h2><p class="muted">仅取消当前演示订单。</p><button class="btn full" id="confirm">确认取消</button>');document.querySelector('#confirm').onclick=()=>{dialog.close();advance('cancelled')}}}
function advance(s){order.status=s;const title={payment:'门店已确认',ready:'模拟付款已完成',stored:'行李已登记寄存',completed:'模拟取件已完成',cancelled:'示例订单已取消'}[s];order.history.push({title,note:'网页演示 · 未执行真实业务操作'});detail();toast(title)}

const chatState={messages:[],data:{items:[],startDate:'',startTime:'',pickupDate:'',pickupTime:'',notes:''},generated:false};
const countNumber=s=>/^\d+$/.test(s)?Number(s):({'一':1,'二':2,'两':2,'三':3,'四':4,'五':5,'六':6,'七':7,'八':8,'九':9,'十':10}[s]||0);
function missingChat(d){return [!d.items.length?'行李数量和尺寸（如两个24寸箱子）':'',!d.startDate?'存入日期':'',!d.startTime?'存入时间':'',!d.pickupDate?'取件日期':'',!d.pickupTime?'取件时间':''].filter(Boolean)}
function parseChat(text,previous){
 const d=structuredClone(previous),found=[];
 // The demo recognises a bounded set of Chinese luggage and schedule phrases.
 const bags=/(\d+|[一二两三四五六七八九十])\s*(?:个|件|只)?\s*(?:(\d{2})\s*寸\s*(?:的)?\s*(?:行李箱|箱子|箱)?|(背包|登机箱|小件|小箱|中箱|大箱))/g;
 for(const m of text.matchAll(bags)){const n=countNumber(m[1]),size=Number(m[2]);const category=m[3]?({'背包':'small','登机箱':'small','小件':'small','小箱':'small','中箱':'medium','大箱':'large'}[m[3]]):size>=20&&size<=26?'medium':size>=27&&size<=30?'large':size>0&&size<20?'small':null;if(category)found.push({category,quantity:n})}
 if(found.length)d.items=found.reduce((rows,i)=>{const existing=rows.find(r=>r.category===i.category);if(existing)existing.quantity+=i.quantity;else rows.push(i);return rows},[]);
 else if(d.items.length===1){const m=text.match(/(?:数量|改成|改为)\s*(\d+|[一二两三四五六七八九十])\s*(?:个|件|只)/);if(m)d.items[0].quantity=countNumber(m[1])}
 let fallback=!d.startDate||!d.startTime?'start':'pickup';
 const chunks=text.replace(/([存取])(?=(?:今天|明天|后天|\d{4}-))/g,'$1，').split(/[，,。；;\n]|然后|再(?=后天|明天|今天|\d)/);
 for(const chunk of chunks){const role=/取|拿|领/.test(chunk)?'pickup':/存|放/.test(chunk)?'start':fallback;
 const date=chunk.match(/(\d{4}-\d{2}-\d{2})|今天|明天|后天/);if(date)d[role+'Date']=date[1]||plus(today,{'今天':0,'明天':1,'后天':2}[date[0]]);
 const t=chunk.match(/(上午|早上|下午|晚上|中午)?\s*(\d{1,2})(?:[:：](\d{2})|点(?:(半)|(\d{1,2})分?)?)/);
 if(t){let h=Number(t[2]),minute=t[3]||t[5]||(t[4]?'30':'00');if(['下午','晚上'].includes(t[1])&&h<12)h+=12;d[role+'Time']=String(h).padStart(2,'0')+':'+minute.padStart(2,'0')}
 if(date||t)fallback='pickup';
 }
 if(/易碎|轻放|特殊|备注|怕压/.test(text))d.notes=text.slice(0,500);
 return d;
}
function chatCandidate(){return {...structuredClone(draft),...structuredClone(chatState.data)}}
function chatError(){const d=chatState.data;if(missingChat(d).length)return '';for(const k of ['startDate','pickupDate']){if(!/^\d{4}-\d{2}-\d{2}$/.test(d[k])||!Number.isFinite(Date.parse(d[k]+'T12:00:00Z'))||new Date(d[k]+'T12:00:00Z').toISOString().slice(0,10)!==d[k])return '日期格式需要是有效的 YYYY-MM-DD。'}if([d.startTime,d.pickupTime].some(t=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(t)))return '请告诉我有效的时间，如 10:00 或下午6点。';return validate(chatCandidate())}
function sendChat(text){if(!text.trim())return;chatState.messages.push({role:'user',text:text.slice(0,1000)});const previous=JSON.stringify(chatState.data);chatState.data=parseChat(text,chatState.data);chatState.generated=false;const missing=missingChat(chatState.data),error=chatError();let reply;if(error)reply=error+' 你可以直接告诉我需要修改的部分。';else if(missing.length)reply=(JSON.stringify(chatState.data)!==previous?'已记下这些安排。':'这个演示支持行李数量、尺寸和存取时间。')+' 还需要：'+missing.join('、')+'。';else reply='安排齐了！请检查右侧信息，点击「生成预约草稿」。需要改动的话，也可以继续告诉我。';chatState.messages.push({role:'assistant',text:reply});}
function generateChat(){const missing=missingChat(chatState.data),error=chatError();if(missing.length||error)return;chatState.generated=true;chatState.messages.push({role:'assistant',text:'预约草稿已生成。确认信息后带入预约表单，再核对联系方式和费用，提交后才会创建示例订单。'});chat()}
function applyChat(){if(!chatState.generated||missingChat(chatState.data).length||chatError())return;draft=chatCandidate();location.hash='booking';toast('已带入预约草稿，请核对后提交')}
function chat(){const d=chatState.data,missing=missingChat(d),error=chatError(),ready=!missing.length&&!error,q=ready?quote(chatCandidate()):null;
 app.innerHTML='<a class="breadcrumb" href="#home">返回服务首页</a>'+heading('AI BOOKING ASSISTANT','说说你的寄存计划','告诉我带了什么、什么时候存取，帮你整理一张预约草稿。')+`<div class="columns chat-columns"><section class="card chat-panel"><div class="row"><h2>寄存小助手</h2><span class="tag">模拟 AI</span></div><p class="chat-disclaimer">规则模拟演示 · 伦敦当地时间 · 请使用示例信息</p><div class="chat-messages" id="messages" role="log" aria-label="与模拟寄存助手的对话" aria-live="polite"><div class="chat-message assistant"><small>寄存小助手</small><p>你好！告诉我行李数量、尺寸和存取时间吧。例如：两个24寸箱子，明天10点存，后天18点取。</p></div>${chatState.messages.map(m=>`<div class="chat-message ${m.role}"><small>${m.role==='user'?'你':'寄存小助手'}</small><p>${esc(m.text)}</p></div>`).join('')}</div><div class="chat-examples"><button type="button" data-example="两个24寸箱子，明天10点存，后天18点取">试试完整安排</button><button type="button" data-example="一个背包，明天上午10点存">我还没想好取件时间</button></div><form id="chat-form"><label class="sr-only" for="chat-input">发送寄存需求</label><div class="chat-compose"><textarea id="chat-input" maxlength="1000" placeholder="输入需求，或说“取件改为后天19点”" required></textarea><button class="btn" type="submit">发送</button></div></form><button class="small-link chat-reset" type="button" id="reset-chat">重新聊一笔</button></section><aside class="card summary chat-draft"><div class="eyebrow">${chatState.generated?'BOOKING DRAFT':'YOUR PLAN'}</div><h2 style="margin-top:12px">${chatState.generated?'预约草稿已生成':'正在整理寄存安排'}</h2><span class="tag">${chatState.generated?'等待你确认':ready?'信息已齐全':'还需补充信息'}</span><div class="divider"></div><div class="summary-line"><span>行李</span><strong>${d.items.length?d.items.map(i=>prices[i.category].name+' × '+i.quantity).join('、'):'待补充'}</strong></div><div class="summary-line"><span>存入</span><strong>${esc(d.startDate||'待补充日期')}<br>${esc(d.startTime||'待补充时间')}</strong></div><div class="summary-line"><span>取件</span><strong>${esc(d.pickupDate||'待补充日期')}<br>${esc(d.pickupTime||'待补充时间')}</strong></div>${d.notes?`<div class="note">备注：${esc(d.notes)}</div>`:''}<div class="divider"></div><div class="muted">预计费用</div><div class="amount">${q?money(q.total):'—'}</div>${q?`<div class="muted">${q.days} 个计费日 · 存入日与取件日均计费</div>`:''}${error?`<p class="error" role="alert">${esc(error)}</p>`:missing.length?`<p class="muted">还需：${missing.join('、')}</p>`:''}<button class="btn full" id="generate-chat" ${ready?'':'disabled'} style="margin-top:22px">${chatState.generated?'重新生成预约草稿':'生成预约草稿'}</button>${chatState.generated?'<button class="btn secondary full" id="apply-chat" style="margin-top:12px">确认并带入预约表单 →</button>':''}<p class="chat-disclaimer">不会自动提交或付款。草稿只保留在当前页面会话，刷新后重置。</p></aside></div>`;
 document.querySelector('#chat-form').onsubmit=e=>{e.preventDefault();const value=document.querySelector('#chat-input').value.trim();if(value){sendChat(value);chat();document.querySelector('#chat-input').focus()}};
 document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{sendChat(b.dataset.example);chat()});document.querySelector('#generate-chat').onclick=generateChat;if(chatState.generated)document.querySelector('#apply-chat').onclick=applyChat;
 document.querySelector('#reset-chat').onclick=()=>{chatState.messages=[];chatState.data={items:[],startDate:'',startTime:'',pickupDate:'',pickupTime:'',notes:''};chatState.generated=false;chat()};const log=document.querySelector('#messages');log.scrollTop=log.scrollHeight;
}
function render(){const r=location.hash.slice(1)||'home';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+(r==='order'?'orders':r==='review'?'booking':r==='chat'?'home':r)));({home,chat,booking,review,orders,order:detail}[r]||home)();window.scrollTo(0,0)}window.onhashchange=render;render();
if(document.modelContext?.registerTool){for(const t of [{name:'open_mock_booking_chat',description:'打开首页的模拟 AI 寄存助手，通过对话整理预约草稿，不提交订单。',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{location.hash='chat';chat();return {page:'chat',mode:'mock'}}},{name:'open_booking_form',description:'打开示例预约表单，不提交订单。',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{location.hash='booking';booking();return {page:'booking'}}},{name:'get_demo_order',description:'读取当前会话的示例订单，不访问真实订单。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({order:order?{id:order.id,status:order.status,total:quote(order.input).total}:null})}])try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{})}catch{}}
